### ISSUE TITLE
Mutt for 918+?

### ISSUE THREAD

**Issue by waltz** [SynoCommunity/spkrepo#40]
Hi all! I noticed that Mutt is in beta on the website. I jiggered the package settings, but it still doesn't show.

Is mutt available for the 918+ series boxes?

Thanks!

**Comment by ymartin59** [comment]
Hello.

First, this is not the right repository to report issue. Should have been: https://github.com/SynoCommunity/spksrc/issues

According to https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model
I confirm package is not available for your model.

Package has not received update since 2016. I have no idea if it may a priority for any contributor.

Regards. Yves

**Comment by waltz** [comment]
Thanks for letting me know. I'll use the correct repository next time when reporting package issues.

I'm curious, how did you figure out that the package is not built for that platform? I don't see any obvious platform requirements in the makefile.
