### ISSUE TITLE
Is there a way to refer to packages hosted somewhere else?

### ISSUE THREAD

**Issue by sztomi** [SynoCommunity/spkrepo#45]
Hi! We are looking into creating an official package source for Plex Media Server. I was wondering if spkrepo is something we could use. From what I understood from the [documentation](https://spkrepo.readthedocs.io/en/latest/api.html#post--api-packages), the API accepts an spk file which the server then stores in the data directory. We are normally hosting our downloads in an S3 bucket and I was wondering if there was a way to simply give spkrepo a URL instead of the file?

**Comment by Diaoul** [comment]
Hi! For now, spkrepo depends on filesystem for storage. This needs to be decoupled to be able to use S3 storage.
I think storage is used for hosting (obviously) but also the package signing process, so an URL won't work.
Spkrepo assumes the server does the signing, but this can be done locally by developers before upload. If that's the case leave `GNUPG_PATH` to None.

PR welcome for this feature! If you plan to work on that we can discuss the workflow with an S3 bucket.

Off the top of my head:
* Should the package already exist in the bucket or is it spkrepo's responsibility to upload it?
* Should spkrepo perform a regular scan of the bucket to import packages or should it be only done by API call?
* Package signing workflow requires to edit the package thus write access to the bucket. How to handle that?

**Comment by sztomi** [comment]
> I think storage is used for hosting (obviously) but also the package signing process, so an URL won't work.

Why not? We are signing our spk packages already (and upload them as such). We don't really need spkrepo to do that for us.

> Should the package already exist in the bucket or is it spkrepo's responsibility to upload it?

In our case, we deploy the files already to S3, and while in some cases it might be nice if spkrepo did upload it, I would consider that an extra feature. For our usecase, this is not needed (in fact, it would be difficult to manage credentials etc.)

> Should spkrepo perform a regular scan of the bucket to import packages or should it be only done by API call?

For our needs, we control both the repo and the bucket, so we can be sure that we always call the API when we uploaded the package.

> Package signing workflow requires to edit the package thus write access to the bucket. How to handle that?

I think this theoretical new endpoint should be a bare-bones feature intended for integration with existing infrastructure. That really only registers the package and the metadata, with storage pointing to a given link (be it S3 or anything else).

**Comment by Diaoul** [comment]
> Why not? We are signing our spk packages already (and upload them as such). We don't really need spkrepo to do that for us.

In order to serve as repository, spkrepo opens the package and extract some data from it, some are stored the the database, others to the fileystem including images to be displayed as icons in the Package Center.
All this is tightly coupled, URLs are not saved to database, instead, they are reconstructed based on the current environment (scheme, host, etc.)

Here are the features I expect from a package repository server:
1. Serve uploaded package and take care of the technical complexity of doing so
2. Trusted Repository with package signing (requires a public keyring)
3. Strong consistency
  * Not possible to overwrite an existing package
  * Conflict detection

Features I consider optional but important:
4. Ability to remove or disable a package
5. Group packages by version (upstream version + spk revision) and manage them as one
6. Group packages by name and manage them as one
7. Signing of uploaded packages (could be separate from the upload endpoint

Contributions are welcome to decouple and abstract all storage-related stuff.
